"use client";
import { HugeiconsIcon } from "@hugeicons/react";
import {
  Home02Icon,
  Search01Icon,
  SparklesIcon,
  MoreHorizontalIcon,
  BellIcon,
  Message01Icon,
  UserCircleIcon,
  UserAdd02Icon,
  Ticket01Icon,
  Logout01Icon,
  Settings02Icon,
  Cancel01Icon,
  ChevronRightIcon,
  Briefcase01Icon,
  UserGroup02Icon,
  UserCheck02Icon,
  HeartIcon,
  Share07Icon,
  Comment01Icon,
  ThumbsUpIcon,
  ThumbsDownIcon,
  DeliveredSentIcon,
  ChevronUpIcon,
  Award01Icon,
  CrownIcon,
  PlusSignIcon,
  Image01Icon,
  Upload04Icon,
  Shield01Icon,
  UserMultiple02Icon,
  Calendar03Icon,
  MapPinIcon,
  PencilEdit02Icon,
  Delete02Icon,
  CheckmarkCircle03Icon,
  AlertCircleIcon,
  StarIcon,
  // ── Additional icons for the new UI ──
  Compass01Icon,
  Rocket01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  SmartPhone01Icon,
  LockIcon,
  ImageAdd02Icon,
  Loading01Icon,
  Clock02Icon,
  CheckmarkCircle01Icon,
  ChevronLeftIcon,
  ChevronDownIcon,
  Mail01Icon,
  Grid02Icon,
  Menu02Icon,
  Medal01Icon,
  InformationCircleIcon,
  BadgeCheckIcon,
  CheckmarkSquare01Icon,
  Settings01Icon,
  Logout02Icon,
  UserStar01Icon,
  MusicNote01Icon,
  PlayCircleIcon,
  Download04Icon,
  File01Icon,
  PauseIcon,
  FilterIcon,
} from "@hugeicons/core-free-icons";

type IconProps = { className?: string; size?: number; strokeWidth?: number };

export function Icon({ name, className, size = 22, strokeWidth }: { name: string } & IconProps) {
  const iconMap: Record<string, any> = {
    home: Home02Icon,
    search: Search01Icon,
    sparkles: SparklesIcon,
    spark: StarIcon,
    star: StarIcon,
    more: MoreHorizontalIcon,
    bell: BellIcon,
    chat: Message01Icon,
    user: UserCircleIcon,
    userPlus: UserAdd02Icon,
    ticket: Ticket01Icon,
    logout: Logout01Icon,
    settings: Settings02Icon,
    x: Cancel01Icon,
    chevronRight: ChevronRightIcon,
    chevronUp: ChevronUpIcon,
    chevronLeft: ChevronLeftIcon,
    chevronDown: ChevronDownIcon,
    briefcase: Briefcase01Icon,
    users: UserGroup02Icon,
    userCheck: UserCheck02Icon,
    userMultiple: UserMultiple02Icon,
    heart: HeartIcon,
    share: Share07Icon,
    comment: Comment01Icon,
    thumbsUp: ThumbsUpIcon,
    thumbsDown: ThumbsDownIcon,
    send: DeliveredSentIcon,
    award: Award01Icon,
    crown: CrownIcon,
    medal: Medal01Icon,
    trophy: Award01Icon,
    plus: PlusSignIcon,
    image: Image01Icon,
    imagePlus: ImageAdd02Icon,
    upload: Upload04Icon,
    shield: Shield01Icon,
    calendar: Calendar03Icon,
    mapPin: MapPinIcon,
    pencil: PencilEdit02Icon,
    trash: Delete02Icon,
    check: CheckmarkCircle03Icon,
    checkCircle: CheckmarkCircle01Icon,
    alert: AlertCircleIcon,
    info: InformationCircleIcon,
    badgeCheck: BadgeCheckIcon,
    checkSquare: CheckmarkSquare01Icon,
    // ── New additions ──
    compass: Compass01Icon,
    rocket: Rocket01Icon,
    arrowLeft: ArrowLeft01Icon,
    arrowRight: ArrowRight01Icon,
    phone: SmartPhone01Icon,
    lock: LockIcon,
    loader: Loading01Icon,
    clock: Clock02Icon,
    mail: Mail01Icon,
    grid: Grid02Icon,
    menu: Menu02Icon,
    settings01: Settings01Icon,
    logout02: Logout02Icon,
    userIdentifier: UserStar01Icon,
    // ── Media icons (post cards) ──
    music: MusicNote01Icon,
    play: PlayCircleIcon,
    download: Download04Icon,
    file: File01Icon,
    pause: PauseIcon,
    filter: FilterIcon,
  };
  const iconData = iconMap[name] || Home02Icon;
  return (
    <HugeiconsIcon
      icon={iconData}
      className={className}
      size={size}
      strokeWidth={strokeWidth}
    />
  );
}

export { HugeiconsIcon };
